# Generated by Django 6.0.6 on 2026-07-07 03:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('categoria', models.CharField(choices=[('HOGAR', 'Hogar (Lavadoras, Refres, etc.)'), ('HERRAMIENTAS', 'Herramientas de trabajo (Taladros, Pulidoras, etc.)'), ('CUIDADO', 'Cuidado personal (Secadoras de pelo, Rasuradoras, etc.)'), ('OTROS', 'Otros')], default='HOGAR', max_length=20)),
                ('aparato_specifico', models.CharField(help_text='Ej. Licuadora 10 velocidades', max_length=100, verbose_name='¿Qué aparato es?')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('falla_descrita', models.TextField(verbose_name='Falla descrita por el cliente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Cotización'), ('ACEPTADO', 'Cotización Aceptada (En Reparación)'), ('RECHAZADO', 'Cotización No Aceptada / Devuelto'), ('REPARADO', 'Listo para Entrega'), ('ENTREGADO', 'Entregado y Cobrado')], default='PENDIENTE', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('requiere_factura', models.BooleanField(default=False)),
            ],
        ),
    ]
