# Generated by Django 6.0.6 on 2026-07-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenreparacion',
            name='dias_garantia',
            field=models.IntegerField(default=10, verbose_name='Días de Garantía'),
        ),
    ]
