# Generated by Django 6.0.6 on 2026-07-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0002_ordenreparacion_dias_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenreparacion',
            name='monto_cotizacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Cotizado ($)'),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='falla_descrita',
            field=models.TextField(blank=True, null=True, verbose_name='Falla descrita por el cliente'),
        ),
    ]
