# Generated by Django 6.0.6 on 2026-07-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0003_ordenreparacion_monto_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenreparacion',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
    ]
