# Generated by Django 6.0.6 on 2026-07-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0004_ordenreparacion_fecha_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Razón Social')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Teléfono (Contacto)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('rfc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RFC')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
