# Generated by Django 6.0.6 on 2026-07-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0005_clientefacturacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. REP-001', max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=150, verbose_name='Descripción del Repuesto')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Stock disponible')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario ($)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
